export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';


export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURHCASE_BURGER_SUCCESS = 'PURHCASE_BURGER_SUCCESS';
export const PURHCASE_BURGER_FAIL = 'PURHCASE_BURGER_FAIL';
export const PURHCASE_INIT = 'PURHCASE_INIT';

